print ("Name: Bryan Jay J. Hizole")
print ("Adress: Bunganay,Boac,Marinduque")
print ("Birthday: November 14 2001")
print ("College: Marinduque State College")
print ("Course: Bachelor of Science in Information Technology")
print ("Year/Section: 2C")